import streamlit as st
import requests
import pandas as pd
import firebase_config  # Triggers Firebase initialization
import os
import resume_processor
import evaluation_engine
from firebase_admin import firestore
from google_auth_oauthlib.flow import Flow
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# Define helper functions
def send_transactional_email(to_email, subject, body_text, sender, password, host="smtp.gmail.com", port=587):
    if not sender or not password:
        raise ValueError("SMTP Sender Email and App Password must be configured to send emails.")
    msg = MIMEMultipart()
    msg['From'] = sender
    msg['To'] = to_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body_text, 'plain', 'utf-8'))
    
    port = int(port)
    if port == 465:
        server = smtplib.SMTP_SSL(host, port)
    else:
        server = smtplib.SMTP(host, port)
        server.starttls()
    server.login(sender, password)
    server.sendmail(sender, to_email, msg.as_string())
    server.quit()

def get_calendar_service():
    credentials = st.session_state.get("credentials")
    if not credentials and os.path.exists("token.json"):
        try:
            credentials = Credentials.from_authorized_user_file("token.json", ['https://www.googleapis.com/auth/calendar.events'])
            st.session_state["credentials"] = credentials
        except Exception:
            credentials = None
            
    if credentials and credentials.expired and credentials.refresh_token:
        try:
            credentials.refresh(Request())
            token_data = {
                'token': credentials.token,
                'refresh_token': credentials.refresh_token,
                'token_uri': credentials.token_uri,
                'client_id': credentials.client_id,
                'client_secret': credentials.client_secret,
                'scopes': credentials.scopes
            }
            with open("token.json", "w") as f:
                json.dump(token_data, f)
            st.session_state["credentials"] = credentials
        except Exception:
            credentials = None
            
    if not credentials:
        return None
    try:
        service = build('calendar', 'v3', credentials=credentials)
        return service
    except Exception:
        return None

def create_interview_event(service, candidate_name, candidate_email, start_time_iso, doc_id):
    from datetime import datetime, timedelta
    start_dt = datetime.fromisoformat(start_time_iso)
    end_dt = start_dt + timedelta(minutes=30)
    event_body = {
        'summary': f'myNachiketa Interview - {candidate_name}',
        'description': f'Technical Interview for candidate {candidate_name} ({candidate_email}) generated by Visl AI Screening Platform.',
        'start': {
            'dateTime': start_dt.isoformat(),
            'timeZone': 'UTC',
        },
        'end': {
            'dateTime': end_dt.isoformat(),
            'timeZone': 'UTC',
        },
        'attendees': [
            {'email': candidate_email},
        ],
        'conferenceData': {
            'createRequest': {
                'requestId': f"meet-{doc_id}-{int(start_dt.timestamp())}",
                'conferenceSolutionKey': {
                    'type': 'hangoutsMeet'
                }
            }
        }
    }
    event = service.events().insert(
        calendarId='primary', 
        body=event_body, 
        conferenceDataVersion=1
    ).execute()
    return event

# Set page configuration with a premium wide layout
st.set_page_config(
    page_title="myNachiketa | Candidate Screening Platform",
    page_icon="💼",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Premium UI CSS injection
st.markdown("""
    <style>
    /* Gradient headers */
    .main-title {
        font-size: 2.8rem;
        font-weight: 800;
        background: linear-gradient(135deg, #6C63FF, #FF6584);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0.5rem;
    }
    .subtitle {
        font-size: 1.2rem;
        color: #7F8C8D;
        margin-bottom: 2rem;
    }
    /* Card style for stats */
    .stat-card {
        background-color: #F8F9FA;
        border-radius: 12px;
        padding: 20px;
        border-left: 5px solid #6C63FF;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
        transition: transform 0.2s ease-in-out;
    }
    .stat-card:hover {
        transform: translateY(-2px);
    }
    /* Status indicator */
    .status-badge {
        display: inline-block;
        padding: 4px 8px;
        border-radius: 12px;
        font-size: 0.85rem;
        font-weight: 600;
    }
    .status-connected {
        background-color: #D4EDDA;
        color: #155724;
    }
    .status-missing {
        background-color: #F8D7DA;
        color: #721C24;
    }
    /* Style for Red Danger Button */
    .stButton > button[kind="primary"] {
        background-color: #FF4B4B !important;
        color: white !important;
        border-color: #FF4B4B !important;
    }
    .stButton > button[kind="primary"]:hover {
        background-color: #FF3333 !important;
        color: white !important;
        border-color: #FF3333 !important;
    }
    </style>
""", unsafe_allow_html=True)

# Main Title and Header Section
st.markdown("<h1 class='main-title'>AI SCREENING PLATFORM</h1>", unsafe_allow_html=True)
st.markdown("<p class='subtitle'>AI-Powered Candidate Screening & Automated Recruitment Workflow</p>", unsafe_allow_html=True)

# Main Navigation Tabs
tab_ingestion, tab_screening, tab_test_admin, tab_interview = st.tabs(['📥 Ingestion', '🧠 AI Screening', '📝 Test Administration', '📅 Final Interview'])

# Sidebar Settings Panel

# Load API keys and tokens from secrets or environment
try:
    gemini_key = st.secrets.get("GEMINI_API_KEY")
except Exception:
    gemini_key = None
if not gemini_key:
    gemini_key = os.environ.get("GEMINI_API_KEY")

try:
    github_token = st.secrets.get("GITHUB_TOKEN")
except Exception:
    github_token = None
if not github_token:
    github_token = os.environ.get("GITHUB_TOKEN")

# Load SMTP configs from secrets/env (supporting standard and custom keys)
try:
    email_sender = st.secrets.get("SMTP_EMAIL") or st.secrets.get("EMAIL_SENDER")
    email_password = st.secrets.get("SMTP_PASSWORD") or st.secrets.get("EMAIL_PASSWORD")
    email_host = st.secrets.get("SMTP_HOST") or st.secrets.get("EMAIL_HOST", "smtp.gmail.com")
    email_port = st.secrets.get("SMTP_PORT") or st.secrets.get("EMAIL_PORT", "587")
except Exception:
    email_sender = None
    email_password = None
    email_host = "smtp.gmail.com"
    email_port = "587"
if not email_sender:
    email_sender = os.environ.get("SMTP_EMAIL") or os.environ.get("EMAIL_SENDER", "")
if not email_password:
    email_password = os.environ.get("SMTP_PASSWORD") or os.environ.get("EMAIL_PASSWORD", "")
if not email_host or email_host == "smtp.gmail.com":
    email_host = os.environ.get("SMTP_HOST") or os.environ.get("EMAIL_HOST", "smtp.gmail.com")
if not email_port or email_port == "587":
    email_port = os.environ.get("SMTP_PORT") or os.environ.get("EMAIL_PORT", "587")

# Load Google OAuth configs from secrets/env
try:
    google_client_id = st.secrets.get("OAUTH_CLIENT_ID") or st.secrets.get("GOOGLE_CLIENT_ID")
    google_client_secret = st.secrets.get("OAUTH_CLIENT_SECRET") or st.secrets.get("GOOGLE_CLIENT_SECRET")
    google_redirect_uri = st.secrets.get("OAUTH_REDIRECT_URI") or st.secrets.get("GOOGLE_REDIRECT_URI", "http://localhost:8501")
except Exception:
    google_client_id = None
    google_client_secret = None
    google_redirect_uri = "http://localhost:8501"
if not google_client_id:
    google_client_id = os.environ.get("OAUTH_CLIENT_ID") or os.environ.get("GOOGLE_CLIENT_ID", "")
if not google_client_secret:
    google_client_secret = os.environ.get("OAUTH_CLIENT_SECRET") or os.environ.get("GOOGLE_CLIENT_SECRET", "")
if not google_redirect_uri or google_redirect_uri == "http://localhost:8501":
    google_redirect_uri = os.environ.get("OAUTH_REDIRECT_URI") or os.environ.get("GOOGLE_REDIRECT_URI", "http://localhost:8501")

# Initialize session state for persistent sidebar text inputs
if "gemini_key_state" not in st.session_state:
    st.session_state["gemini_key_state"] = gemini_key or ""
if "github_token_state" not in st.session_state:
    st.session_state["github_token_state"] = github_token or ""
if "smtp_email_state" not in st.session_state:
    st.session_state["smtp_email_state"] = email_sender or ""
if "smtp_password_state" not in st.session_state:
    st.session_state["smtp_password_state"] = email_password or ""
if "smtp_host_state" not in st.session_state:
    st.session_state["smtp_host_state"] = email_host or "smtp.gmail.com"
if "smtp_port_state" not in st.session_state:
    st.session_state["smtp_port_state"] = str(email_port) or "587"
if "oauth_client_id_state" not in st.session_state:
    st.session_state["oauth_client_id_state"] = google_client_id or ""
if "oauth_client_secret_state" not in st.session_state:
    st.session_state["oauth_client_secret_state"] = google_client_secret or ""
if "oauth_redirect_uri_state" not in st.session_state:
    st.session_state["oauth_redirect_uri_state"] = google_redirect_uri or "http://localhost:8501"

# Sidebar API Override / Configurations
st.sidebar.markdown("---")
st.sidebar.markdown("### 🔑 API Configuration")
user_gemini_key = st.sidebar.text_input(
    "Gemini API Key", 
    type="password",
    help="Default loaded from environment or secrets.",
    key="gemini_key_state"
)
user_github_token = st.sidebar.text_input(
    "GitHub Token (GITHUB_TOKEN)", 
    type="password",
    help="Used to fetch candidate READMEs and language statistics.",
    key="github_token_state"
)

# Expandable sections for SMTP and Calendar OAuth
with st.sidebar.expander("📧 Email Settings (SMTP)"):
    user_email_sender = st.text_input("Sender Email", key="smtp_email_state")
    user_email_password = st.text_input("App Password", type="password", key="smtp_password_state")
    user_email_host = st.text_input("SMTP Host", key="smtp_host_state")
    user_email_port = st.text_input("SMTP Port", key="smtp_port_state")

with st.sidebar.expander("🗓️ Google Calendar API (OAuth)"):
    user_google_client_id = st.text_input("OAuth Client ID", key="oauth_client_id_state")
    user_google_client_secret = st.text_input("OAuth Client Secret", type="password", key="oauth_client_secret_state")
    user_google_redirect_uri = st.text_input("OAuth Redirect URI", key="oauth_redirect_uri_state")

# Resolve final credentials from persistent session state keys
gemini_key = st.session_state["gemini_key_state"]
github_token = st.session_state["github_token_state"]
email_sender = st.session_state["smtp_email_state"]
email_password = st.session_state["smtp_password_state"]
email_host = st.session_state["smtp_host_state"]
email_port = st.session_state["smtp_port_state"]
google_client_id = st.session_state["oauth_client_id_state"]
google_client_secret = st.session_state["oauth_client_secret_state"]
google_redirect_uri = st.session_state["oauth_redirect_uri_state"]

# OAuth callback handled inside the Final Interview tab directly

# Sidebar System Health Status
st.sidebar.markdown("---")
st.sidebar.markdown("### ⚙️ System Status")

# Check Firebase Status
import firebase_admin
has_firebase_config = False
try:
    has_firebase_config = "firebase" in st.secrets
except Exception:
    pass

db_client = None
try:
    db_client = firebase_config.init_firebase()
except Exception:
    pass

if has_firebase_config or firebase_admin._apps or db_client is not None:
    st.sidebar.markdown(
        'Firestore: <span class="status-badge status-connected">Connected</span>',
        unsafe_allow_html=True
    )
else:
    st.sidebar.markdown(
        'Firestore: <span class="status-badge status-missing">Config Missing</span>',
        unsafe_allow_html=True
    )

# Check Gemini API Status
if gemini_key:
    st.sidebar.markdown(
        'Gemini API: <span class="status-badge status-connected">Connected</span>',
        unsafe_allow_html=True
    )
else:
    st.sidebar.markdown(
        'Gemini API: <span class="status-badge status-missing">API Key Missing</span>',
        unsafe_allow_html=True
    )

# Check GitHub Token Status
if github_token:
    st.sidebar.markdown(
        'GitHub API: <span class="status-badge status-connected">Token Configured</span>',
        unsafe_allow_html=True
    )
else:
    st.sidebar.markdown(
        'GitHub API: <span class="status-badge status-missing">No Token (Rate Limited)</span>',
        unsafe_allow_html=True
    )

# Reset Database Button (Danger Zone)
st.sidebar.markdown("---")
st.sidebar.markdown("### ⚠️ Danger Zone")
if st.sidebar.button("Danger: Reset Database", use_container_width=True, type="primary"):
    from firebase_config import db
    if db is not None:
        try:
            candidates_ref = db.collection("candidates")
            docs = list(candidates_ref.stream())
            if not docs:
                st.sidebar.info("Database is already empty.")
            else:
                for doc in docs:
                    doc.reference.delete()
                st.sidebar.success(f"Deleted {len(docs)} candidates!")
                st.rerun()
        except Exception as e:
            st.sidebar.error(f"Error resetting database: {e}")

# Sidebar Footer
st.sidebar.markdown("---")
st.sidebar.markdown("<small>Founding AI Engineer Assignment</small>", unsafe_allow_html=True)


# Render Ingestion View inside Tab 1
with tab_ingestion:
    st.header("📥 Candidate Ingestion & Dataset Upload")
    st.write(
        "Upload your candidate data sheets (Excel .xlsx files) and parse incoming details "
        "including Name, Email, GitHub handles, and Resume download paths."
    )
    
    col1, col2 = st.columns([2, 1])
    with col1:
        st.subheader("Upload Candidate Dataset")
        uploaded_file = st.file_uploader(
            "Choose an Excel (.xlsx) file", 
            type=["xlsx"]
        )
        if uploaded_file is not None:
            try:
                # Read the response sheet specifically
                df = pd.read_excel(uploaded_file, sheet_name='Response')
                st.success("File uploaded and read successfully!")
                st.write("### Dataset Preview (First 3 Rows)", df.head(3))
                
                if st.button("Start Ingesting Candidates", use_container_width=True):
                    from firebase_config import db
                    if db is None:
                        st.error("Firestore database is not connected. Ingestion failed.")
                    else:
                        with st.spinner("Ingesting candidates to Firestore..."):
                            count = 0
                            for _, row in df.iterrows():
                                email = str(row.get("email")).strip()
                                if not email or email == "nan":
                                    continue
                                
                                # Convert row to clean dict (remove NaNs)
                                doc_data = {}
                                for col_name, val in row.items():
                                    if pd.isna(val):
                                        doc_data[col_name] = ""
                                    else:
                                        if isinstance(val, (int, float)):
                                            doc_data[col_name] = val
                                        else:
                                            doc_data[col_name] = str(val).strip()
                                
                                # Set initial status
                                doc_data["status"] = "PENDING_RESUME"
                                
                                # Write to Firestore (auto-generate Document ID)
                                db.collection("candidates").document().set(doc_data)
                                count += 1
                                
                            st.success(f"Successfully ingested {count} candidates into Firestore!")
                            
                            # Start the background resume processing thread
                            if resume_processor.start_resume_processing():
                                st.info("Background resume processing thread started.")
                            else:
                                st.info("Resume processing worker is already running in the background.")
            except Exception as e:
                st.error(f"Error reading file: {e}")
                
    with col2:
        st.subheader("Ingestion Guidelines")
        st.info(
            "The uploaded Excel sheet must contain the **Response** sheet with these columns:\n"
            "- **s_no**: Serial number\n"
            "- **name**: Candidate Name\n"
            "- **email**: Primary Email ID (used as document key)\n"
            "- **college**: College Name\n"
            "- **branch**: Major or Department\n"
            "- **cgpa**: GPA score\n"
            "- **best_ai_project**: Detail of best project\n"
            "- **research_work**: Description of research work\n"
            "- **github**: GitHub profile link\n"
            "- **resume**: Google Drive link to Resume PDF"
        )
    
    st.markdown("---")
    
    # Render progress monitoring fragment
    @st.fragment(run_every=3)
    def display_ingestion_progress():
        from firebase_config import db
        if db is None:
            return
            
        try:
            candidates = list(db.collection("candidates").stream())
        except Exception as e:
            st.error(f"Error querying candidates: {e}")
            return
            
        if not candidates:
            st.info("No candidates in the database yet. Upload a dataset to begin.")
            return
            
        # Count statuses
        total = len(candidates)
        pending = sum(1 for c in candidates if c.to_dict().get("status") == "PENDING_RESUME")
        parsed = sum(1 for c in candidates if c.to_dict().get("status") == "RESUME_PARSED")
        evaluated = sum(1 for c in candidates if c.to_dict().get("status") == "AI_EVALUATED")
        shortlisted_test = sum(1 for c in candidates if c.to_dict().get("status") == "SHORTLISTED_FOR_TEST")
        test_sent = sum(1 for c in candidates if c.to_dict().get("status") == "TEST_LINK_SENT")
        test_completed = sum(1 for c in candidates if c.to_dict().get("status") == "TEST_COMPLETED")
        ready_interview = sum(1 for c in candidates if c.to_dict().get("status") == "READY_FOR_SHORTLIST")
        scheduled = sum(1 for c in candidates if c.to_dict().get("status") == "INTERVIEW_SCHEDULED")
        rejected = sum(1 for c in candidates if c.to_dict().get("status") == "REJECTED")
        failed_res = sum(1 for c in candidates if c.to_dict().get("status") == "FAILED_RESUME")
        failed_eval = sum(1 for c in candidates if c.to_dict().get("status") == "FAILED_EVALUATION")
        
        st.markdown("### Ingestion & Funnel Progress Status")
        
        # Check if worker is running
        is_running = resume_processor._worker_running
        status_indicator = "🟢 Processing resumes in background..." if is_running else "⚪ Idle"
        
        col_status_1, col_status_2 = st.columns([3, 1])
        with col_status_1:
            st.caption(f"Background Process Status: **{status_indicator}** (Refreshing every 3s)")
        with col_status_2:
            if pending > 0 and not is_running:
                if st.button("Resume Worker", use_container_width=True):
                    resume_processor.start_resume_processing()
                    st.rerun()
                    
        col1, col2, col3, col4, col5, col6 = st.columns(6)
        col1.metric("Total Candidates", total)
        col2.metric("Parsed Resumes", parsed)
        col3.metric("AI Evaluated", evaluated)
        col4.metric("Test Phase", shortlisted_test + test_sent + test_completed)
        col5.metric("Interview Shortlist", ready_interview + scheduled)
        col6.metric("Rejected / Failed", f"{rejected} / {failed_res + failed_eval}")
        
        # Detail Table
        data = []
        for c in candidates:
            d = c.to_dict()
            data.append({
                "S.No": d.get("s_no", ""),
                "Name": d.get("name", "N/A"),
                "Email": d.get("email", "N/A"),
                "Status": d.get("status", "PENDING_RESUME"),
                "Skill Match": d.get("skill_match_score", "N/A"),
                "Project Depth": d.get("project_depth_score", "N/A"),
                "Academic Score": d.get("academic_score", "N/A"),
                "Composite Score": d.get("composite_score", "N/A")
            })
        df_status = pd.DataFrame(data).sort_values("S.No").reset_index(drop=True)
        st.dataframe(df_status, use_container_width=True)
        
        # Candidate Profile Explorer Card
        st.markdown("### 🔍 Candidate Profile & Evaluation Explorer")
        candidate_names = [f"{c.to_dict().get('name', 'N/A')} ({c.to_dict().get('email', 'N/A')})" for c in candidates]
        selected_candidate_str = st.selectbox("Select Candidate to view detailed AI evaluations & scheduling info:", candidate_names)
        
        if selected_candidate_str:
            idx = candidate_names.index(selected_candidate_str)
            selected_c = candidates[idx]
            d = selected_c.to_dict()
            
            # Format UI card
            col_info, col_scores = st.columns(2)
            with col_info:
                st.markdown(f"#### 👤 {d.get('name', 'N/A')}")
                st.write(f"**Email**: {d.get('email', 'N/A')}")
                st.write(f"**College**: {d.get('college', 'N/A')}")
                st.write(f"**Branch**: {d.get('branch', 'N/A')}")
                st.write(f"**CGPA**: {d.get('cgpa', 'N/A')}")
                st.write(f"**Current Pipeline Status**: `{d.get('status', 'PENDING_RESUME')}`")
                
                # Show interview info if scheduled
                if d.get("status") == "INTERVIEW_SCHEDULED":
                    st.success(f"🗓️ **Interview Scheduled**\n\n**Time (UTC)**: {d.get('interview_time')}\n\n[Join Google Meet]({d.get('google_meet_link')})")
                elif d.get("status") == "INVITED":
                    st.info("✉️ **Invitation Sent**\n\nWaiting for candidate to schedule an interview.")
                    
            with col_scores:
                st.markdown("#### 📊 Evaluation Scores")
                st.write(f"**Skill Match**: {d.get('skill_match_score', 'N/A')}/10")
                st.write(f"**Project Depth**: {d.get('project_depth_score', 'N/A')}/10")
                st.write(f"**Academic Score**: {d.get('academic_score', 'N/A')}/10")
                st.write(f"**Composite Score**: {d.get('composite_score', 'N/A')}/100")
                
                la_score = d.get("test_la")
                code_score = d.get("test_code")
                if la_score is not None:
                    st.write(f"**Logical Aptitude Test**: {la_score}/100")
                if code_score is not None:
                    st.write(f"**Coding Test**: {code_score}/100")
                    
            # Reasoning
            reasoning = d.get("explainable_reasoning")
            if reasoning:
                st.markdown("#### 🧠 AI Explainable Reasoning Analysis")
                st.info(reasoning)
                
            # GitHub info if available
            git_meta = d.get("github_metadata")
            if git_meta and isinstance(git_meta, dict) and "repos" in git_meta:
                st.markdown("#### 🐙 GitHub Repositories Summary")
                for r in git_meta["repos"]:
                    st.markdown(f"**{r.get('name')}** | ⭐ {r.get('stars')} stars | Language: `{r.get('primary_language')}`")

    display_ingestion_progress()

with tab_screening:
    st.header("🔍 AI Screening & Candidate Evaluation")
    st.write(
        "Evaluate candidates dynamically using AI models. Parse resumes, perform repository-level "
        "analysis on candidate GitHub accounts, and compare relevance against the Job Description."
    )
    
    # Job Description Input
    st.subheader("Job Description")
    job_desc = st.text_area(
        "Enter the Job Description (JD) to evaluate candidates against:",
        height=150,
        placeholder="We are looking for a Founding AI Engineer with experience in Streamlit, LLMs..."
    )
    
    col1, col2, col3 = st.columns(3)
    with col1:
        st.markdown(
            '<div style="background-color: rgba(255, 255, 255, 0.05); padding: 25px; border-radius: 12px; display: flex; justify-content: center; align-items: center; margin-bottom: 15px; border: 1px solid rgba(255,255,255,0.1);">'
            '<img src="https://cdn-icons-png.flaticon.com/512/337/337946.png" style="width: 80px;">'
            '</div>',
            unsafe_allow_html=True
        )
        st.subheader("1. Parse Resumes")
        st.caption("Extract resume text, education, and technical experience using LLM-guided parsing.")
        if st.button("Start Resume Extraction", use_container_width=True):
            with st.spinner("Physically extracting text from resumes..."):
                count, err = resume_processor.process_resumes_synchronously()
                if err:
                    st.error(f"Error extracting resumes: {err}")
                else:
                    st.success(f"Resume extraction completed successfully! Processed {count} resumes.")
                    st.toast(f"✅ Extracted {count} resumes!")
            st.rerun()
            
    with col2:
        st.markdown(
            '<div style="background-color: rgba(255, 255, 255, 0.05); padding: 25px; border-radius: 12px; display: flex; justify-content: center; align-items: center; margin-bottom: 15px; border: 1px solid rgba(255,255,255,0.1);">'
            '<img src="https://cdn-icons-png.flaticon.com/512/25/25231.png" style="width: 80px; filter: invert(0.8);">'
            '</div>',
            unsafe_allow_html=True
        )
        st.subheader("2. GitHub Analysis")
        st.caption("Inspect repositories, contribution depth, and code quality on candidates' GitHub accounts.")
        if st.button("Start GitHub Repository Analysis", use_container_width=True):
            with st.spinner("Analyzing candidate GitHub repositories..."):
                res = evaluation_engine.run_github_analysis_only(github_token=github_token)
                if "error" in res:
                    st.error(res["error"])
                else:
                    st.success(f"Successfully analyzed GitHub profiles for {res['processed']} candidates!")
            
    with col3:
        st.markdown(
            '<div style="background-color: rgba(255, 255, 255, 0.05); padding: 25px; border-radius: 12px; display: flex; justify-content: center; align-items: center; margin-bottom: 15px; border: 1px solid rgba(255,255,255,0.1);">'
            '<img src="https://cdn-icons-png.flaticon.com/512/2103/2103810.png" style="width: 80px;">'
            '</div>',
            unsafe_allow_html=True
        )
        st.subheader("3. Evaluate & Rank")
        st.caption("Compare resume and github profile against the Job Description and generate scores.")
        if st.button("Trigger AI Screening", use_container_width=True):
            if not job_desc.strip():
                st.error("Please enter a Job Description first.")
            elif not gemini_key:
                st.error("Gemini API key is not configured. Please add it to your settings.")
            else:
                with st.spinner("Running structured AI evaluation against the Job Description..."):
                    res = evaluation_engine.run_candidate_evaluation_pipeline(
                        job_description=job_desc,
                        github_token=github_token,
                        gemini_api_key=gemini_key
                    )
                    if "error" in res:
                        st.error(res["error"])
                    else:
                        st.success(f"Evaluated {res['processed']} candidates successfully!")
                        for candidate in res.get("results", []):
                            if candidate.get("status") == "Success":
                                scores = candidate["scores"]
                                st.write(f"✅ **{candidate['name']}**: Skill: {scores['skill_match']}/10, Project: {scores['project_depth']}/10, Academic: {scores['academic']}/10")
                            else:
                                st.write(f"❌ **{candidate['name']}**: Failed - {candidate.get('error')}")

    # Render AI Gating and Standings
    st.markdown("---")
    st.subheader("⚙️ AI Screening Gating & Test Shortlisting")
    ai_threshold = st.slider(
        "Minimum AI Score Threshold", 
        min_value=0.0, 
        max_value=10.0, 
        value=6.5, 
        step=0.1,
        key="ai_screening_threshold"
    )
    
    from firebase_config import db
    if db is not None:
        try:
            candidates_ref = db.collection("candidates")
            all_docs = list(candidates_ref.stream())
        except Exception as e:
            st.error(f"Error loading candidates: {e}")
            all_docs = []
            
        shortlisted_for_test_preview = []
        rejected_preview = []
        
        for doc in all_docs:
            d = doc.to_dict()
            d["doc_id"] = doc.id
            status = d.get("status")
            skill = d.get("skill_match_score")
            
            if skill is not None:
                skill = float(skill)
                proj = float(d.get("project_depth_score", 0))
                acad = float(d.get("academic_score", 0))
                ai_score = round((skill + proj + acad) / 3.0, 2)
                
                candidate_entry = {
                    "Name": d.get("name", "N/A"),
                    "Email": d.get("email", "N/A"),
                    "Skill Match": skill,
                    "Project Depth": proj,
                    "Academic": acad,
                    "AI Score": ai_score,
                    "Current Status": status,
                    "doc_id": d["doc_id"]
                }
                
                # Real-time filtering based on threshold slider
                if ai_score >= ai_threshold:
                    shortlisted_for_test_preview.append(candidate_entry)
                else:
                    rejected_preview.append(candidate_entry)
                    
        # Render two tables side-by-side or stacked
        col_s_table, col_r_table = st.columns(2)
        with col_s_table:
            st.markdown("#### ✅ Shortlisted for Test (AI Score >= Threshold)")
            if shortlisted_for_test_preview:
                df_s_preview = pd.DataFrame(shortlisted_for_test_preview).drop(columns=["doc_id", "Current Status"]).sort_values("AI Score", ascending=False).reset_index(drop=True)
                df_s_preview.index += 1
                st.dataframe(df_s_preview, use_container_width=True)
            else:
                st.info("No candidates qualify for the test phase at this threshold.")
                
        with col_r_table:
            st.markdown("#### ❌ Rejected (AI Score < Threshold)")
            if rejected_preview:
                df_r_preview = pd.DataFrame(rejected_preview).drop(columns=["doc_id", "Current Status"]).sort_values("AI Score", ascending=False).reset_index(drop=True)
                df_r_preview.index += 1
                st.dataframe(df_r_preview, use_container_width=True)
            else:
                st.info("No candidates rejected at this threshold.")
                
        # Save AI Shortlist button
        if st.button("💾 Save AI Shortlist", use_container_width=True):
            try:
                with st.spinner("Saving shortlist statuses to database..."):
                    count_shortlisted = 0
                    count_rejected = 0
                    for c in shortlisted_for_test_preview:
                        # Only update if current status is in [AI_EVALUATED, SHORTLISTED_FOR_TEST, REJECTED]
                        if c["Current Status"] in ["AI_EVALUATED", "SHORTLISTED_FOR_TEST", "REJECTED"]:
                            db.collection("candidates").document(c["doc_id"]).update({
                                "status": "SHORTLISTED_FOR_TEST",
                                "ai_score": c["AI Score"],
                                "gated_at_test": firestore.SERVER_TIMESTAMP
                            })
                            count_shortlisted += 1
                            
                    for c in rejected_preview:
                        if c["Current Status"] in ["AI_EVALUATED", "SHORTLISTED_FOR_TEST", "REJECTED"]:
                            db.collection("candidates").document(c["doc_id"]).update({
                                "status": "REJECTED",
                                "ai_score": c["AI Score"]
                            })
                            count_rejected += 1
                            
                st.success(f"Shortlist saved successfully! Gated {count_shortlisted} to Shortlisted for Test and {count_rejected} to Rejected.")
                st.rerun()
            except Exception as e:
                st.error(f"Error saving AI Shortlist: {e}")

with tab_test_admin:
    st.header("📝 Test Administration")
    st.write(
        "Deliver standardized assessment links to qualified candidates and process test score sheets "
        "containing coding and logical aptitude results."
    )
    
    from firebase_config import db
    if db is not None:
        # 1. Deliver Assessment Links
        st.subheader("Deliver Standardized Tests")
        try:
            candidates_ref = db.collection("candidates")
            shortlisted_test_docs = list(candidates_ref.where("status", "==", "SHORTLISTED_FOR_TEST").stream())
        except Exception as e:
            st.error(f"Error querying shortlisted candidates: {e}")
            shortlisted_test_docs = []
            
        st.write(f"Candidates pending test link delivery: **{len(shortlisted_test_docs)}**")
        
        if len(shortlisted_test_docs) > 0:
            if st.button("✉️ Send Assessment Links", use_container_width=True):
                if not email_sender or not email_password:
                    st.error("Please configure SMTP settings (Email & App Password) in the sidebar first.")
                else:
                    with st.spinner("Simulating sending standardized test links via SMTP..."):
                        sent_count = 0
                        for doc in shortlisted_test_docs:
                            d = doc.to_dict()
                            c_email = d.get("email")
                            c_name = d.get("name", "Candidate")
                            
                            subject = "myNachiketa Candidate Assessment Link"
                            body = f"Dear {c_name},\n\nYou have successfully cleared our AI screening phase. Please complete the following technical assessment link within 48 hours:\nhttps://assessment-portal.mynachiketa.com/test?email={c_email}\n\nBest regards,\nmyNachiketa Recruitment Team"
                            
                            try:
                                send_transactional_email(
                                    to_email=c_email,
                                    subject=subject,
                                    body_text=body,
                                    sender=email_sender,
                                    password=email_password,
                                    host=email_host,
                                    port=email_port
                                )
                                doc.reference.update({
                                    "status": "TEST_LINK_SENT",
                                    "test_link_sent_at": firestore.SERVER_TIMESTAMP
                                })
                                sent_count += 1
                                st.toast(f"✅ Test link sent to {c_name}")
                            except Exception as err:
                                st.error(f"Failed to email {c_name}: {err}")
                                
                        st.success(f"Successfully sent assessment links to {sent_count} candidates!")
                        st.rerun()
                        
        # 2. Upload test results
        st.write("---")
        st.subheader("Upload Candidate Test Result Sheet")
        st.write("Upload the spreadsheet (Excel .xlsx containing the 'Test Result' sheet) to input candidate test scores.")
        
        uploaded_test_sheet = st.file_uploader(
            "Choose Excel file (.xlsx) containing 'Test Result' sheet", 
            type=["xlsx"],
            key="test_sheet_uploader"
        )
        
        if uploaded_test_sheet is not None:
            try:
                df_test = pd.read_excel(uploaded_test_sheet, sheet_name='Test Result')
                st.success("Test Result sheet loaded successfully!")
                st.write("### Test Results Preview", df_test.head(3))
                
                if st.button("Upload & Process Test Scores", use_container_width=True):
                    with st.spinner("Processing test scores and updating pipeline states..."):
                        processed_count = 0
                        for _, row in df_test.iterrows():
                            email_val = str(row.get("email")).strip()
                            if not email_val or email_val == "nan":
                                continue
                                
                            # Query candidate by email field
                            docs = list(db.collection("candidates").where("email", "==", email_val).stream())
                            if not docs:
                                st.warning(f"No candidate document found with email: {email_val}")
                                continue
                                
                            test_la = float(row.get("test_la", 0))
                            test_code = float(row.get("test_code", 0))
                            
                            for doc in docs:
                                d = doc.to_dict()
                                # Only process test scores for candidates who have been evaluated by AI
                                skill = float(d.get("skill_match_score", 0))
                                proj = float(d.get("project_depth_score", 0))
                                acad = float(d.get("academic_score", 0))
                                ai_avg = (skill + proj + acad) / 3.0
                                
                                # Formula: (0.4 * (ai_avg) * 10.0) + (0.3 * test_la) + (0.3 * test_code)
                                comp_score = (0.4 * ai_avg * 10.0) + (0.3 * test_la) + (0.3 * test_code)
                                comp_score = round(comp_score, 2)
                                
                                # Write to Firestore and update status to TEST_COMPLETED
                                doc.reference.update({
                                    "test_la": test_la,
                                    "test_code": test_code,
                                    "composite_score": comp_score,
                                    "status": "TEST_COMPLETED",
                                    "processed_at_test": firestore.SERVER_TIMESTAMP
                                })
                                processed_count += 1
                                
                        st.success(f"Successfully processed test scores for {processed_count} candidate records!")
                        st.rerun()
            except Exception as e:
                st.error(f"Error reading file or sheet: {e}")
                
        # 3. Display current test standings
        st.write("---")
        st.subheader("🏆 Candidate Test Stage Standings")
        
        try:
            test_candidates = list(db.collection("candidates").stream())
        except Exception as e:
            st.error(f"Error querying test standings: {e}")
            test_candidates = []
            
        test_rows = []
        for doc in test_candidates:
            d = doc.to_dict()
            status = d.get("status")
            if status in ["SHORTLISTED_FOR_TEST", "TEST_LINK_SENT", "TEST_COMPLETED", "READY_FOR_SHORTLIST", "INTERVIEW_SCHEDULED", "REJECTED"]:
                test_rows.append({
                    "Name": d.get("name", "N/A"),
                    "Email": d.get("email", "N/A"),
                    "Logical Aptitude": d.get("test_la", "N/A"),
                    "Coding Score": d.get("test_code", "N/A"),
                    "Composite Score": d.get("composite_score", "N/A"),
                    "Status": status
                })
                
        if test_rows:
            df_test_standings = pd.DataFrame(test_rows).reset_index(drop=True)
            df_test_standings.index += 1
            st.dataframe(df_test_standings, use_container_width=True)
        else:
            st.info("No candidates have entered the test administration phase yet.")

with tab_interview:
    st.header("📅 Final Interview")
    st.write(
        "Set composite score thresholds to shortlist candidates for final interviews, "
        "review custom drafts, send invitation emails, and schedule Google Meet calls."
    )
    
    from firebase_config import db
    if db is not None:
        # 1. Google Calendar API Connection
        st.subheader("🔗 Google Calendar API Integration")
        
        is_authenticated = "credentials" in st.session_state
        if not is_authenticated:
            if os.path.exists("token.json"):
                try:
                    credentials = Credentials.from_authorized_user_file("token.json", ['https://www.googleapis.com/auth/calendar.events'])
                    st.session_state["credentials"] = credentials
                    is_authenticated = True
                except Exception:
                    pass
                    
        if not is_authenticated:
            if not google_client_id or not google_client_secret:
                st.info("To connect Google Calendar, please enter your OAuth Client ID and Secret in the sidebar.")
            else:
                client_config = {
                    "web": {
                        "client_id": google_client_id,
                        "project_id": "google-calendar-project",
                        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                        "token_uri": "https://oauth2.googleapis.com/token",
                        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                        "client_secret": google_client_secret,
                        "redirect_uris": [google_redirect_uri]
                    }
                }
                try:
                    flow = Flow.from_client_config(
                        client_config, 
                        scopes=['https://www.googleapis.com/auth/calendar.events']
                    )
                    flow.redirect_uri = google_redirect_uri
                    
                    if "code" in st.query_params:
                        # User returned from Google
                        code_verifier = None
                        if os.path.exists("oauth_cache.json"):
                            with open("oauth_cache.json", "r") as f:
                                cache = json.load(f)
                                code_verifier = cache.get("code_verifier")
                                
                        # Reconstruct the token exchange request manually using the cached verifier
                        token_url = "https://oauth2.googleapis.com/token"
                        payload = {
                            'client_id': google_client_id,
                            'client_secret': google_client_secret,
                            'code': st.query_params['code'],
                            'grant_type': 'authorization_code',
                            'redirect_uri': google_redirect_uri,
                            'code_verifier': code_verifier
                        }
                        response = requests.post(token_url, data=payload)
                        token_data = response.json()
                        
                        if 'access_token' in token_data:
                            creds = Credentials(
                                token=token_data['access_token'],
                                refresh_token=token_data.get('refresh_token'),
                                token_uri=token_url,
                                client_id=google_client_id,
                                client_secret=google_client_secret,
                                scopes=['https://www.googleapis.com/auth/calendar.events']
                            )
                            st.session_state['credentials'] = creds
                            
                            # Save credentials to token.json
                            token_json_data = {
                                'token': creds.token,
                                'refresh_token': creds.refresh_token,
                                'token_uri': creds.token_uri,
                                'client_id': creds.client_id,
                                'client_secret': creds.client_secret,
                                'scopes': creds.scopes
                            }
                            with open("token.json", "w") as f:
                                json.dump(token_json_data, f)
                                
                            # Clean up the cache file
                            if os.path.exists("oauth_cache.json"):
                                try:
                                    os.remove("oauth_cache.json")
                                except Exception:
                                    pass
                                    
                            st.query_params.clear()
                            st.success("Successfully authenticated with Google Calendar!")
                            st.rerun()
                        else:
                            st.error(f"Token exchange failed: {token_data}")
                    else:
                        auth_url, state = flow.authorization_url(prompt='consent', access_type='offline')
                        st.session_state['oauth_state'] = state
                        st.session_state['code_verifier'] = flow.code_verifier
                        
                        # Write the verifier to a local cache file to pass it to the new tab
                        with open("oauth_cache.json", "w") as f:
                            json.dump({"code_verifier": flow.code_verifier}, f)
                            
                        st.link_button("🔑 Authenticate with Google", auth_url, use_container_width=True)
                except Exception as e:
                    st.error(f"Error building OAuth Flow: {e}")
        else:
            st.success("🟢 Connected to Google Calendar API")
            
        # 2. Shortlist for Interview Gating
        st.write("---")
        st.subheader("⚙️ Final Selection Gating")
        try:
            candidates_ref = db.collection("candidates")
            all_candidates_docs = list(candidates_ref.stream())
        except Exception as e:
            st.error(f"Error querying candidates: {e}")
            all_candidates_docs = []
            
        comp_threshold = st.slider(
            "Minimum Composite Score Threshold", 
            min_value=0, 
            max_value=100, 
            value=65, 
            step=1,
            key="interview_shortlist_threshold"
        )
        
        shortlisted_interview_preview = []
        rejected_interview_preview = []
        
        for doc in all_candidates_docs:
            d = doc.to_dict()
            d["doc_id"] = doc.id
            status = d.get("status")
            comp_score = d.get("composite_score")
            
            if comp_score is not None:
                comp_score = float(comp_score)
                candidate_entry = {
                    "Name": d.get("name", "N/A"),
                    "Email": d.get("email", "N/A"),
                    "Composite Score": comp_score,
                    "Current Status": status,
                    "doc_id": d["doc_id"]
                }
                
                # Real-time filtering based on composite score threshold slider
                if comp_score >= comp_threshold:
                    shortlisted_interview_preview.append(candidate_entry)
                else:
                    rejected_interview_preview.append(candidate_entry)
                    
        # Render two tables side-by-side or stacked
        col_s_int, col_r_int = st.columns(2)
        with col_s_int:
            st.markdown("#### ✅ Shortlisted for Interview (Composite Score >= Threshold)")
            if shortlisted_interview_preview:
                df_s_int = pd.DataFrame(shortlisted_interview_preview).drop(columns=["doc_id", "Current Status"]).sort_values("Composite Score", ascending=False).reset_index(drop=True)
                df_s_int.index += 1
                st.dataframe(df_s_int, use_container_width=True)
            else:
                st.info("No candidates qualify for the final interview at this threshold.")
                
        with col_r_int:
            st.markdown("#### ❌ Rejected (Composite Score < Threshold)")
            if rejected_interview_preview:
                df_r_int = pd.DataFrame(rejected_interview_preview).drop(columns=["doc_id", "Current Status"]).sort_values("Composite Score", ascending=False).reset_index(drop=True)
                df_r_int.index += 1
                st.dataframe(df_r_int, use_container_width=True)
            else:
                st.info("No candidates rejected at this threshold.")
                
        # Save Final Shortlist button
        if st.button("💾 Save Final Shortlist", use_container_width=True):
            try:
                with st.spinner("Saving final shortlist statuses to database..."):
                    count_shortlisted = 0
                    count_rejected = 0
                    for c in shortlisted_interview_preview:
                        # Only update if status is in [TEST_COMPLETED, READY_FOR_SHORTLIST, REJECTED]
                        if c["Current Status"] in ["TEST_COMPLETED", "READY_FOR_SHORTLIST", "REJECTED"]:
                            db.collection("candidates").document(c["doc_id"]).update({
                                "status": "READY_FOR_SHORTLIST",
                                "shortlisted_for_interview_at": firestore.SERVER_TIMESTAMP
                            })
                            count_shortlisted += 1
                            
                    for c in rejected_interview_preview:
                        if c["Current Status"] in ["TEST_COMPLETED", "READY_FOR_SHORTLIST", "REJECTED"]:
                            db.collection("candidates").document(c["doc_id"]).update({
                                "status": "REJECTED"
                            })
                            count_rejected += 1
                            
                st.success(f"Final shortlist saved successfully! Shortlisted {count_shortlisted} for final interview; rejected {count_rejected}.")
                st.rerun()
            except Exception as e:
                st.error(f"Error saving final shortlist: {e}")
                    
        # 3. Draft & Review Email Campaign & Scheduling
        try:
            candidates_ref = db.collection("candidates")
            all_candidates = list(candidates_ref.stream())
        except Exception as e:
            st.error(f"Error loading candidates: {e}")
            all_candidates = []
            
        shortlisted_candidates = []
        for doc in all_candidates:
            d = doc.to_dict()
            d["doc_id"] = doc.id
            if d.get("status") == "READY_FOR_SHORTLIST":
                shortlisted_candidates.append({
                    "Name": d.get("name", "N/A"),
                    "Email": d.get("email", "N/A"),
                    "Composite Score": d.get("composite_score", 0),
                    "doc_id": d["doc_id"]
                })
                
        if shortlisted_candidates:
            st.write("---")
            st.subheader("✉️ Email Campaign Draft & Review")
            
            # Global Email Template
            default_template = """Dear {name},

Thank you for applying to myNachiketa. We are pleased to inform you that you have been shortlisted for an interview based on your composite score of {score}.

Please join your technical interview using this Google Meet link: {meet_link}

Best regards,
myNachiketa recruitment Team"""

            email_template = st.text_area("Global Email Template", value=default_template, height=180, help="Use {name}, {score}, and {meet_link} placeholders.")
            
            # Global Interview Time Picker
            st.write("#### 📅 Choose Interview Time for Dispatched Invites")
            col_d_disp, col_t_disp = st.columns(2)
            with col_d_disp:
                disp_date = st.date_input("Interview Date:", key="disp_date_input_interview")
            with col_t_disp:
                disp_time = st.time_input("Interview Start Time (UTC):", key="disp_time_input_interview")
                
            # Setup session state for shortlisted dataframe
            if "interview_shortlist_df" not in st.session_state:
                data_rows = []
                for c in shortlisted_candidates:
                    data_rows.append({
                        "Send Invite": True,
                        "Name": c["Name"],
                        "Email": c["Email"],
                        "Score": c["Composite Score"],
                        "Draft Message": "",
                        "doc_id": c["doc_id"]
                    })
                st.session_state["interview_shortlist_df"] = pd.DataFrame(data_rows)
                
            # Toggle Select All
            if "select_all_interview_state" not in st.session_state:
                st.session_state["select_all_interview_state"] = True
                
            select_all = st.checkbox("Toggle Select All", value=st.session_state["select_all_interview_state"], key="toggle_select_all_interview")
            if select_all != st.session_state["select_all_interview_state"]:
                st.session_state["interview_shortlist_df"]["Send Invite"] = select_all
                st.session_state["select_all_interview_state"] = select_all
                
            # Generate Drafts button
            if st.button("📝 Generate Email Drafts", use_container_width=True, key="gen_drafts_interview"):
                from datetime import datetime
                start_dt = datetime.combine(disp_date, disp_time)
                start_time_iso = start_dt.isoformat()
                
                service = get_calendar_service()
                df = st.session_state["interview_shortlist_df"]
                
                with st.spinner("Generating Google Meet links and draft emails..."):
                    for idx, row in df.iterrows():
                        c_name = row["Name"]
                        c_email = row["Email"]
                        c_score = row["Score"]
                        c_doc_id = row["doc_id"]
                        
                        meet_link = "https://meet.google.com/mock-meet-link"
                        if service is not None:
                            try:
                                event = create_interview_event(
                                    service=service,
                                    candidate_name=c_name,
                                    candidate_email=c_email,
                                    start_time_iso=start_time_iso,
                                    doc_id=c_doc_id
                                )
                                meet_link = event.get('hangoutLink')
                                if not meet_link:
                                    entry_points = event.get('conferenceData', {}).get('entryPoints', [])
                                    for ep in entry_points:
                                        if ep.get('entryPointType') == 'video':
                                            meet_link = ep.get('uri')
                                            break
                                if not meet_link:
                                    meet_link = "https://meet.google.com/new"
                            except Exception as ex:
                                st.warning(f"Could not schedule event for {c_name}: {ex}. Using mock Meet link.")
                        else:
                            st.warning("Google Calendar API is not connected. Drafts will use mock Meet link.")
                            
                        formatted_msg = email_template.format(name=c_name, score=c_score, meet_link=meet_link)
                        df.at[idx, "Draft Message"] = formatted_msg
                        df.at[idx, "generated_meet_link"] = meet_link
                        df.at[idx, "generated_interview_time"] = start_time_iso
                        
                st.session_state["interview_shortlist_df"] = df
                st.success("Successfully generated drafts! Review and edit them in the table below.")
                st.rerun()
                
            # Render Table
            st.write("#### Edit Candidate Invites and Drafts")
            edited_df = st.data_editor(
                st.session_state["interview_shortlist_df"],
                use_container_width=True,
                column_config={
                    "doc_id": None,
                    "generated_meet_link": None,
                    "generated_interview_time": None
                },
                key="interview_data_editor"
            )
            st.session_state["interview_shortlist_df"] = edited_df
            
            # Confirm and Send Emails
            if st.button("✉️ Confirm & Send Emails", use_container_width=True, key="send_emails_interview"):
                if not email_sender or not email_password:
                    st.error("Please configure SMTP settings (Email & App Password) in the sidebar.")
                else:
                    with st.spinner("Delivering emails and updating status to INTERVIEW_SCHEDULED..."):
                        sent_count = 0
                        for idx, row in edited_df.iterrows():
                            if row["Send Invite"]:
                                c_name = row["Name"]
                                c_email = row["Email"]
                                c_doc_id = row["doc_id"]
                                draft_msg = row["Draft Message"]
                                meet_link = row.get("generated_meet_link", "https://meet.google.com/mock-meet-link")
                                interview_time = row.get("generated_interview_time", "")
                                
                                if not draft_msg:
                                    st.warning(f"Skipped {c_name} (Draft Message is empty). Generate drafts first.")
                                    continue
                                    
                                try:
                                    send_transactional_email(
                                        to_email=c_email,
                                        subject="Interview Invitation & Confirmation - myNachiketa",
                                        body_text=draft_msg,
                                        sender=email_sender,
                                        password=email_password,
                                        host=email_host,
                                        port=email_port
                                    )
                                    
                                    db.collection("candidates").document(c_doc_id).update({
                                        "status": "INTERVIEW_SCHEDULED",
                                        "google_meet_link": meet_link,
                                        "interview_time": interview_time,
                                        "email_body_sent": draft_msg,
                                        "invited_at": firestore.SERVER_TIMESTAMP
                                    })
                                    
                                    st.toast(f"✅ Email successfully sent to {c_name}")
                                    st.success(f"Email successfully sent to {c_name} ({c_email})")
                                    sent_count += 1
                                except Exception as err:
                                    st.error(f"Failed to email {c_name}: {err}")
                                    
                        if sent_count > 0:
                            del st.session_state["interview_shortlist_df"]
                            if "select_all_interview_state" in st.session_state:
                                del st.session_state["select_all_interview_state"]
                            st.success(f"Successfully sent {sent_count} invitation emails!")
                            st.rerun()
        else:
            st.info("No candidates currently shortlisted for interview. Adjust the Composite threshold slider and click 'Shortlist for Interview' first.")
            
        # 4. Invited Candidates Dashboard Display
        st.markdown("---")
        st.subheader("✉️ Invited & Scheduled Candidates")
        
        invited_list = []
        for doc in all_candidates:
            d = doc.to_dict()
            if d.get("status") == "INTERVIEW_SCHEDULED":
                invited_list.append({
                    "Name": d.get("name", "N/A"),
                    "Email": d.get("email", "N/A"),
                    "Composite Score": d.get("composite_score", 0),
                    "Interview Time": d.get("interview_time", "N/A"),
                    "Google Meet Link": d.get("google_meet_link", "N/A")
                })
                
        if invited_list:
            df_invited = pd.DataFrame(invited_list).sort_values("Composite Score", ascending=False).reset_index(drop=True)
            df_invited.index += 1
            st.dataframe(df_invited, use_container_width=True)
        else:
            st.info("No candidates have been scheduled or invited yet.")
